### ISSUE TITLE
I'm having problems compiling the talko sketches

### ISSUE THREAD

**Issue by Ginsengbob** [deladriere/euro-modules#2]
I'm getting the same errors you are getting.
Thanks

**Comment by deladriere** [comment]
I think I will try this solution : https://github.com/DatanoiseTV/Talkie/commit/b5fc23bdc6c9bd593191d30e6f5290b2175aeac2

**Comment by deladriere** [comment]
Can you try this new version : It works for me with Arduino 1.6.4
Please remember to place talkie2.h and talkie2.cpp under .../libraries/talkie2

**Comment by Ginsengbob** [comment]
I'm using 1.6.5
ok I did that.
I'm still getting compiling errors.
There is a talkie2 in my libraries with talkie2.h and talkie2.cpp in it.   But... a talko_1 in my sketchbook as an ino.

**Comment by Ginsengbob** [comment]
time.h ....no such file or directory
is what it says

**Comment by deladriere** [comment]
You need to install the Time library :  http://playground.arduino.cc/code/time

**Comment by Ginsengbob** [comment]
Ok 
I did that and now it freezes when I try to verify it.
Thanks for spending time helping me. 
I basically picked up Arduino after seeing and hearing your demo.
I really hope i can get this working.

**Comment by deladriere** [comment]
what do mean by freezing ?
What do you mean by verify ?
can you run the Tom's dinner demo an play with the pitch / speed / bend ?

**Comment by Ginsengbob** [comment]
freezing = it starts loading the sketch and the status bar gets stuck about 1/4 of the way through.
I have to reset the program.
Verify is  a button on the ide next to upload that basically just checks the sketch without uploading it. It also freezes when I use this function.

I did get tom's diner to run but I couldn't figure out how to hook up the pitch / speed / or bend .
How do I hook up the pitch / speed and bend potentiometers? 
Also how do I hook up the gate button and mode pot?

thanks

**Comment by deladriere** [comment]
please have a look here : https://github.com/deladriere/euro-modules/blob/master/Talko/Hardware/talko_basic.png

You will not display the mode but all function will works

**Comment by Ginsengbob** [comment]
Hey
I'm out of town til Monday. Thank you for all of your help.
I will try this when I get home.

Chris

On 5/27/2015 12:41 AM, deladriere wrote:

> please have a look here : 
> https://github.com/deladriere/euro-modules/blob/master/Talko/Hardware/talko_basic.png
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/deladriere/euro-modules/issues/2#issuecomment-105763642.

---

This email has been checked for viruses by Avast antivirus software.
http://www.avast.com
